create table public.trains (
    id bigint generated by default as identity primary key,
    train_number text not null unique,
    train_name text not null,
    source text not null,
    destination text not null,
    departure_time text not null,
    arrival_time text not null,
    duration text not null,
    seats_available integer not null default 0 check (seats_available >= 0),
    price numeric(10, 2) not null check (price >= 0),
    train_class text not null
);

create table public.reservations (
    id bigint generated by default as identity primary key,
    passenger_name text not null,
    email text not null,
    train_id bigint not null references public.trains(id),
    travel_date date not null,
    seats integer not null check (seats between 1 and 5),
    total_amount numeric(10, 2) not null check (total_amount >= 0),
    status text not null default 'Confirmed'
        check (status in ('Confirmed', 'Cancelled')),
    created_at timestamptz not null default now()
);

grant select on public.trains to anon;
grant select, insert, update on public.reservations to anon;

alter table public.trains enable row level security;
alter table public.reservations enable row level security;

create policy "Demo users can read trains"
    on public.trains for select to anon
    using (true);

create policy "Demo users can read reservations"
    on public.reservations for select to anon
    using (true);

create policy "Demo users can create reservations"
    on public.reservations for insert to anon
    with check (true);

create policy "Demo users can update reservations"
    on public.reservations for update to anon
    using (true)
    with check (true);

insert into public.trains (
    train_number,
    train_name,
    source,
    destination,
    departure_time,
    arrival_time,
    duration,
    seats_available,
    price,
    train_class
)
values
    (
        '12007',
        'Shatabdi Express',
        'Bengaluru',
        'Chennai',
        '06:00',
        '10:50',
        '4h 50m',
        28,
        850,
        'CC'
    ),
    (
        '99901',
        'Example Intercity',
        'Bengaluru',
        'Chennai',
        '07:30',
        '13:00',
        '5h 30m',
        40,
        700,
        '2S'
    );